name: countie
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"
    
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  http: ^0.13.4
  draggable_bottom_sheet: ^0.1.2
  material_design_icons_flutter: 5.0.6595
  table_calendar: ^3.0.4
  google_fonts: ^2.3.1
  flutter_signin_button: ^2.0.0
  
  cupertino_icons: ^1.0.2
  syncfusion_flutter_charts: ^19.4.53

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0


flutter:

  uses-material-design: true

